# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/vladimirsizonenko/Documents/GitHub/traffic_analyzer/gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1000, 531)
        MainWindow.setMinimumSize(QtCore.QSize(1000, 500))
        MainWindow.setMaximumSize(QtCore.QSize(1000, 531))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setLineWidth(0)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame = QtWidgets.QFrame(self.frame_2)
        self.frame.setMinimumSize(QtCore.QSize(71, 0))
        self.frame.setMaximumSize(QtCore.QSize(71, 16777215))
        self.frame.setStyleSheet("border: none")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setLineWidth(0)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.to_page_home = QtWidgets.QPushButton(self.frame)
        self.to_page_home.setMinimumSize(QtCore.QSize(0, 70))
        self.to_page_home.setStyleSheet("QPushButton {    \n"
"    \n"
"    background-image: url(:/24x24/icons/24x24/cil-home.png);\n"
"    background-position: center;\n"
"    background-repeat: no-repeat;\n"
"    border: none;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(33, 37, 43);\n"
"}\n"
"QPushButton:pressed {    \n"
"\n"
"    background-color: rgb(85, 170, 255);\n"
"}")
        self.to_page_home.setText("")
        self.to_page_home.setObjectName("to_page_home")
        self.verticalLayout_2.addWidget(self.to_page_home)
        self.to_page_action = QtWidgets.QPushButton(self.frame)
        self.to_page_action.setMinimumSize(QtCore.QSize(0, 70))
        self.to_page_action.setStyleSheet("QPushButton {    \n"
"    \n"
"    background-image: url(:/24x24/icons/24x24/cil-equalizer.png);\n"
"    background-position: center;\n"
"    background-repeat: no-repeat;\n"
"    border: none;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(33, 37, 43);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgb(85, 170, 255);\n"
"}")
        self.to_page_action.setText("")
        self.to_page_action.setObjectName("to_page_action")
        self.verticalLayout_2.addWidget(self.to_page_action)
        self.to_page_graph = QtWidgets.QPushButton(self.frame)
        self.to_page_graph.setMinimumSize(QtCore.QSize(0, 70))
        self.to_page_graph.setStyleSheet("QPushButton {    \n"
"    \n"
"    background-position: center;\n"
"    background-image: url(:/24x24/icons/24x24/cil-chart-line.png);\n"
"    background-repeat: no-repeat;\n"
"    border: none;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(33, 37, 43);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgb(85, 170, 255);\n"
"}")
        self.to_page_graph.setText("")
        self.to_page_graph.setObjectName("to_page_graph")
        self.verticalLayout_2.addWidget(self.to_page_graph)
        self.to_page_setting = QtWidgets.QPushButton(self.frame)
        self.to_page_setting.setMinimumSize(QtCore.QSize(0, 70))
        self.to_page_setting.setStyleSheet("QPushButton {    \n"
"    background-image: url(:/24x24/icons/24x24/cil-settings.png);\n"
"       \n"
"        background-position: center;\n"
"    background-repeat: no-repeat;\n"
"    border: none;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(33, 37, 43);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgb(85, 170, 255);\n"
"}")
        self.to_page_setting.setText("")
        self.to_page_setting.setObjectName("to_page_setting")
        self.verticalLayout_2.addWidget(self.to_page_setting)
        self.horizontalLayout_2.addWidget(self.frame)
        self.frame_3 = QtWidgets.QFrame(self.frame_2)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame_4 = QtWidgets.QFrame(self.frame_3)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setSpacing(0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.stackedWidget = QtWidgets.QStackedWidget(self.frame_4)
        self.stackedWidget.setAutoFillBackground(False)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_action = QtWidgets.QWidget()
        self.page_action.setObjectName("page_action")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.page_action)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.groupBox_17 = QtWidgets.QGroupBox(self.page_action)
        self.groupBox_17.setTitle("")
        self.groupBox_17.setObjectName("groupBox_17")
        self.gridLayout_17 = QtWidgets.QGridLayout(self.groupBox_17)
        self.gridLayout_17.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_17.setSpacing(0)
        self.gridLayout_17.setObjectName("gridLayout_17")
        self.groupBox_18 = QtWidgets.QGroupBox(self.groupBox_17)
        self.groupBox_18.setTitle("")
        self.groupBox_18.setObjectName("groupBox_18")
        self.gridLayout_18 = QtWidgets.QGridLayout(self.groupBox_18)
        self.gridLayout_18.setObjectName("gridLayout_18")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_18.addItem(spacerItem, 0, 0, 1, 1)
        self.export_to_xls_ = QtWidgets.QPushButton(self.groupBox_18)
        self.export_to_xls_.setMinimumSize(QtCore.QSize(80, 20))
        self.export_to_xls_.setMaximumSize(QtCore.QSize(80, 20))
        self.export_to_xls_.setStyleSheet("QPushButton {    \n"
"        background-position: center;\n"
"    background-repeat: no-repeat;\n"
"    border: none;\n"
"    background-color: rgb(102, 102, 102);\n"
"    border: 2px solid rgb(128, 128, 128);\n"
"    border-radius: 5px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(33, 37, 43);\n"
"}\n"
"QPushButton:pressed {    \n"
"\n"
"    background-color: rgb(85, 170, 255);\n"
"}")
        self.export_to_xls_.setObjectName("export_to_xls_")
        self.gridLayout_18.addWidget(self.export_to_xls_, 0, 1, 1, 1)
        self.gridLayout_17.addWidget(self.groupBox_18, 2, 0, 1, 1)
        self.groupBox_19 = QtWidgets.QGroupBox(self.groupBox_17)
        self.groupBox_19.setTitle("")
        self.groupBox_19.setObjectName("groupBox_19")
        self.gridLayout_19 = QtWidgets.QGridLayout(self.groupBox_19)
        self.gridLayout_19.setObjectName("gridLayout_19")
        self.Client = QtWidgets.QComboBox(self.groupBox_19)
        self.Client.setMinimumSize(QtCore.QSize(162, 26))
        self.Client.setStyleSheet("background-color: rgba(0, 0, 0, 0);\n"
"color: rgb(208, 208, 208);\n"
"font: 25 12pt \"Segoe UI Light\";")
        self.Client.setObjectName("Client")
        self.gridLayout_19.addWidget(self.Client, 0, 3, 1, 1)
        self.label_40 = QtWidgets.QLabel(self.groupBox_19)
        self.label_40.setObjectName("label_40")
        self.gridLayout_19.addWidget(self.label_40, 0, 2, 1, 1)
        self.from_data = QtWidgets.QDateTimeEdit(self.groupBox_19)
        self.from_data.setObjectName("from_data")
        self.gridLayout_19.addWidget(self.from_data, 0, 1, 1, 1)
        self.ANI = QtWidgets.QLineEdit(self.groupBox_19)
        self.ANI.setEnabled(True)
        self.ANI.setAcceptDrops(True)
        self.ANI.setAutoFillBackground(False)
        self.ANI.setStyleSheet("background-color: rgba(0, 0, 0, 0);\n"
"color: rgb(208, 208, 208);\n"
"font: 25 12pt \"Segoe UI Light\";")
        self.ANI.setInputMethodHints(QtCore.Qt.ImhNone)
        self.ANI.setInputMask("")
        self.ANI.setText("")
        self.ANI.setFrame(False)
        self.ANI.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.ANI.setAlignment(QtCore.Qt.AlignCenter)
        self.ANI.setDragEnabled(False)
        self.ANI.setReadOnly(False)
        self.ANI.setClearButtonEnabled(False)
        self.ANI.setObjectName("ANI")
        self.gridLayout_19.addWidget(self.ANI, 2, 5, 1, 1)
        self.label_41 = QtWidgets.QLabel(self.groupBox_19)
        self.label_41.setObjectName("label_41")
        self.gridLayout_19.addWidget(self.label_41, 0, 4, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.groupBox_19)
        self.label_13.setObjectName("label_13")
        self.gridLayout_19.addWidget(self.label_13, 0, 0, 1, 1)
        self.line_17 = QtWidgets.QFrame(self.groupBox_19)
        self.line_17.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_17.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_17.setObjectName("line_17")
        self.gridLayout_19.addWidget(self.line_17, 3, 3, 1, 1)
        self.label_42 = QtWidgets.QLabel(self.groupBox_19)
        self.label_42.setObjectName("label_42")
        self.gridLayout_19.addWidget(self.label_42, 2, 2, 1, 1)
        self.setTable = QtWidgets.QPushButton(self.groupBox_19)
        self.setTable.setMinimumSize(QtCore.QSize(80, 20))
        self.setTable.setMaximumSize(QtCore.QSize(80, 20))
        self.setTable.setStyleSheet("QPushButton {    \n"
"        background-position: center;\n"
"    background-repeat: no-repeat;\n"
"    border: none;\n"
"    border: 2px solid rgb(128, 128, 128);\n"
"    background-color: rgb(102, 102, 102);\n"
"    border-radius: 5px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(33, 37, 43);\n"
"}\n"
"QPushButton:pressed {    \n"
"\n"
"    background-color: rgb(85, 170, 255);\n"
"}")
        self.setTable.setObjectName("setTable")
        self.gridLayout_19.addWidget(self.setTable, 4, 3, 1, 1)
        self.line_18 = QtWidgets.QFrame(self.groupBox_19)
        self.line_18.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_18.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_18.setObjectName("line_18")
        self.gridLayout_19.addWidget(self.line_18, 1, 3, 1, 1)
        self.MCCMNC = QtWidgets.QLineEdit(self.groupBox_19)
        self.MCCMNC.setEnabled(True)
        self.MCCMNC.setAcceptDrops(True)
        self.MCCMNC.setAutoFillBackground(False)
        self.MCCMNC.setStyleSheet("background-color: rgba(0, 0, 0, 0);\n"
"color: rgb(208, 208, 208);\n"
"font: 25 12pt \"Segoe UI Light\";")
        self.MCCMNC.setInputMethodHints(QtCore.Qt.ImhNone)
        self.MCCMNC.setInputMask("")
        self.MCCMNC.setText("")
        self.MCCMNC.setFrame(False)
        self.MCCMNC.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.MCCMNC.setAlignment(QtCore.Qt.AlignCenter)
        self.MCCMNC.setDragEnabled(False)
        self.MCCMNC.setReadOnly(False)
        self.MCCMNC.setClearButtonEnabled(False)
        self.MCCMNC.setObjectName("MCCMNC")
        self.gridLayout_19.addWidget(self.MCCMNC, 2, 3, 1, 1)
        self.label_43 = QtWidgets.QLabel(self.groupBox_19)
        self.label_43.setObjectName("label_43")
        self.gridLayout_19.addWidget(self.label_43, 2, 4, 1, 1)
        self.Vendor = QtWidgets.QComboBox(self.groupBox_19)
        self.Vendor.setMinimumSize(QtCore.QSize(162, 26))
        self.Vendor.setStyleSheet("background-color: rgba(0, 0, 0, 0);\n"
"color: rgb(208, 208, 208);\n"
"font: 25 12pt \"Segoe UI Light\";")
        self.Vendor.setObjectName("Vendor")
        self.gridLayout_19.addWidget(self.Vendor, 0, 5, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_19.addItem(spacerItem1, 4, 4, 1, 1)
        self.label_44 = QtWidgets.QLabel(self.groupBox_19)
        self.label_44.setObjectName("label_44")
        self.gridLayout_19.addWidget(self.label_44, 2, 0, 1, 1)
        self.line_19 = QtWidgets.QFrame(self.groupBox_19)
        self.line_19.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_19.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_19.setObjectName("line_19")
        self.gridLayout_19.addWidget(self.line_19, 1, 5, 1, 1)
        self.line_20 = QtWidgets.QFrame(self.groupBox_19)
        self.line_20.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_20.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_20.setObjectName("line_20")
        self.gridLayout_19.addWidget(self.line_20, 3, 5, 1, 1)
        self.to_date = QtWidgets.QDateTimeEdit(self.groupBox_19)
        self.to_date.setObjectName("to_date")
        self.gridLayout_19.addWidget(self.to_date, 2, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_19.addItem(spacerItem2, 4, 0, 1, 3)
        self.setGraph = QtWidgets.QPushButton(self.groupBox_19)
        self.setGraph.setMinimumSize(QtCore.QSize(80, 20))
        self.setGraph.setMaximumSize(QtCore.QSize(80, 20))
        self.setGraph.setStyleSheet("QPushButton {    \n"
"        background-position: center;\n"
"    background-repeat: no-repeat;\n"
"    border: none;\n"
"    background-color: rgb(102, 102, 102);\n"
"    border: 2px solid rgb(128, 128, 128);\n"
"    border-radius: 5px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(33, 37, 43);\n"
"}\n"
"QPushButton:pressed {    \n"
"\n"
"    background-color: rgb(85, 170, 255);\n"
"}")
        self.setGraph.setObjectName("setGraph")
        self.gridLayout_19.addWidget(self.setGraph, 4, 5, 1, 1)
        self.gridLayout_17.addWidget(self.groupBox_19, 1, 0, 1, 1)
        self.verticalLayout_8.addWidget(self.groupBox_17)
        self.TABLE = QtWidgets.QTableWidget(self.page_action)
        self.TABLE.setAlternatingRowColors(True)
        self.TABLE.setObjectName("TABLE")
        self.TABLE.setColumnCount(10)
        self.TABLE.setRowCount(10)
        item = QtWidgets.QTableWidgetItem()
        self.TABLE.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.TABLE.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.TABLE.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.TABLE.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.TABLE.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.TABLE.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.TABLE.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.TABLE.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.TABLE.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.TABLE.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.TABLE.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.TABLE.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.TABLE.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.TABLE.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.TABLE.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.TABLE.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.TABLE.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.TABLE.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.TABLE.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.TABLE.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.TABLE.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.TABLE.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.TABLE.setItem(1, 0, item)
        self.verticalLayout_8.addWidget(self.TABLE)
        self.stackedWidget.addWidget(self.page_action)
        self.page_home = QtWidgets.QWidget()
        self.page_home.setObjectName("page_home")
        self.stackedWidget.addWidget(self.page_home)
        self.page_chart = QtWidgets.QWidget()
        self.page_chart.setObjectName("page_chart")
        self.webGraph = QtWebEngineWidgets.QWebEngineView(self.page_chart)
        self.webGraph.setGeometry(QtCore.QRect(10, 10, 901, 471))
        self.webGraph.setStyleSheet("background-color: rgb(102, 102, 102);")
        self.webGraph.setUrl(QtCore.QUrl("about:blank"))
        self.webGraph.setObjectName("webGraph")
        self.stackedWidget.addWidget(self.page_chart)
        self.page_setting = QtWidgets.QWidget()
        self.page_setting.setObjectName("page_setting")
        self.groupBox_20 = QtWidgets.QGroupBox(self.page_setting)
        self.groupBox_20.setGeometry(QtCore.QRect(30, 40, 871, 181))
        self.groupBox_20.setMinimumSize(QtCore.QSize(871, 181))
        self.groupBox_20.setObjectName("groupBox_20")
        self.gridLayout_20 = QtWidgets.QGridLayout(self.groupBox_20)
        self.gridLayout_20.setObjectName("gridLayout_20")
        self.cdrtime_5 = QtWidgets.QCheckBox(self.groupBox_20)
        self.cdrtime_5.setObjectName("cdrtime_5")
        self.gridLayout_20.addWidget(self.cdrtime_5, 0, 0, 1, 1)
        self.sender_id_5 = QtWidgets.QCheckBox(self.groupBox_20)
        self.sender_id_5.setObjectName("sender_id_5")
        self.gridLayout_20.addWidget(self.sender_id_5, 0, 1, 1, 1)
        self.vendor_ani_5 = QtWidgets.QCheckBox(self.groupBox_20)
        self.vendor_ani_5.setObjectName("vendor_ani_5")
        self.gridLayout_20.addWidget(self.vendor_ani_5, 0, 2, 1, 1)
        self.duration_5 = QtWidgets.QCheckBox(self.groupBox_20)
        self.duration_5.setObjectName("duration_5")
        self.gridLayout_20.addWidget(self.duration_5, 0, 3, 1, 1)
        self.client_product_5 = QtWidgets.QCheckBox(self.groupBox_20)
        self.client_product_5.setObjectName("client_product_5")
        self.gridLayout_20.addWidget(self.client_product_5, 0, 4, 1, 1)
        self.msg_id_5 = QtWidgets.QCheckBox(self.groupBox_20)
        self.msg_id_5.setObjectName("msg_id_5")
        self.gridLayout_20.addWidget(self.msg_id_5, 1, 0, 1, 1)
        self.trnsc_id_5 = QtWidgets.QCheckBox(self.groupBox_20)
        self.trnsc_id_5.setObjectName("trnsc_id_5")
        self.gridLayout_20.addWidget(self.trnsc_id_5, 1, 1, 1, 1)
        self.send_time_5 = QtWidgets.QCheckBox(self.groupBox_20)
        self.send_time_5.setObjectName("send_time_5")
        self.gridLayout_20.addWidget(self.send_time_5, 1, 2, 1, 1)
        self.mccmnc_10 = QtWidgets.QCheckBox(self.groupBox_20)
        self.mccmnc_10.setObjectName("mccmnc_10")
        self.gridLayout_20.addWidget(self.mccmnc_10, 1, 3, 1, 1)
        self.vendor_product_5 = QtWidgets.QCheckBox(self.groupBox_20)
        self.vendor_product_5.setObjectName("vendor_product_5")
        self.gridLayout_20.addWidget(self.vendor_product_5, 1, 4, 1, 1)
        self.status_5 = QtWidgets.QCheckBox(self.groupBox_20)
        self.status_5.setObjectName("status_5")
        self.gridLayout_20.addWidget(self.status_5, 2, 0, 1, 1)
        self.text_sms_5 = QtWidgets.QCheckBox(self.groupBox_20)
        self.text_sms_5.setObjectName("text_sms_5")
        self.gridLayout_20.addWidget(self.text_sms_5, 2, 1, 1, 1)
        self.stackedWidget.addWidget(self.page_setting)
        self.verticalLayout_9.addWidget(self.stackedWidget)
        self.verticalLayout_3.addWidget(self.frame_4)
        self.status_bar = QtWidgets.QFrame(self.frame_3)
        self.status_bar.setMinimumSize(QtCore.QSize(0, 15))
        self.status_bar.setMaximumSize(QtCore.QSize(16777215, 15))
        self.status_bar.setStyleSheet("border: none")
        self.status_bar.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.status_bar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.status_bar.setObjectName("status_bar")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.status_bar)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem3 = QtWidgets.QSpacerItem(460, 12, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.progressBar = QtWidgets.QProgressBar(self.status_bar)
        self.progressBar.setMinimumSize(QtCore.QSize(0, 15))
        self.progressBar.setMaximumSize(QtCore.QSize(16777215, 15))
        self.progressBar.setStyleSheet("QProgressBar {\n"
"    border: none\n"
"   \n"
"\n"
"}\n"
"::chunk {\n"
"    \n"
"    background-color: rgb(128, 128, 128);\n"
"    width: 15px; \n"
"    margin: 0.5px;\n"
"}")
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.horizontalLayout.addWidget(self.progressBar)
        self.verticalLayout_3.addWidget(self.status_bar)
        self.horizontalLayout_2.addWidget(self.frame_3)
        self.verticalLayout.addWidget(self.frame_2)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.export_to_xls_.setText(_translate("MainWindow", "export"))
        self.label_40.setText(_translate("MainWindow", "     Client:"))
        self.ANI.setPlaceholderText(_translate("MainWindow", "ANI"))
        self.label_41.setText(_translate("MainWindow", "<html><head/><body><p align=\"right\">                                      Vendor</p></body></html>"))
        self.label_13.setText(_translate("MainWindow", "From"))
        self.label_42.setText(_translate("MainWindow", "MCCMNC"))
        self.setTable.setText(_translate("MainWindow", "Run"))
        self.MCCMNC.setPlaceholderText(_translate("MainWindow", "MCCMNC"))
        self.label_43.setText(_translate("MainWindow", "<html><head/><body><p align=\"right\">                                           ANI</p></body></html>"))
        self.label_44.setText(_translate("MainWindow", "to"))
        self.setGraph.setText(_translate("MainWindow", "GraphView"))
        item = self.TABLE.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.TABLE.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "2"))
        item = self.TABLE.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "3"))
        item = self.TABLE.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "4"))
        item = self.TABLE.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "5"))
        item = self.TABLE.verticalHeaderItem(5)
        item.setText(_translate("MainWindow", "6"))
        item = self.TABLE.verticalHeaderItem(6)
        item.setText(_translate("MainWindow", "7"))
        item = self.TABLE.verticalHeaderItem(7)
        item.setText(_translate("MainWindow", "8"))
        item = self.TABLE.verticalHeaderItem(8)
        item.setText(_translate("MainWindow", "9"))
        item = self.TABLE.verticalHeaderItem(9)
        item.setText(_translate("MainWindow", "10"))
        item = self.TABLE.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.TABLE.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "2"))
        item = self.TABLE.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "3"))
        item = self.TABLE.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "4"))
        item = self.TABLE.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "5"))
        item = self.TABLE.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "6"))
        item = self.TABLE.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "7"))
        item = self.TABLE.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "8"))
        item = self.TABLE.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "9"))
        item = self.TABLE.horizontalHeaderItem(9)
        item.setText(_translate("MainWindow", "10"))
        __sortingEnabled = self.TABLE.isSortingEnabled()
        self.TABLE.setSortingEnabled(False)
        item = self.TABLE.item(0, 0)
        item.setText(_translate("MainWindow", "1/1"))
        item = self.TABLE.item(0, 1)
        item.setText(_translate("MainWindow", "2/1"))
        item = self.TABLE.item(1, 0)
        item.setText(_translate("MainWindow", "1/2"))
        self.TABLE.setSortingEnabled(__sortingEnabled)
        self.groupBox_20.setTitle(_translate("MainWindow", "Export Setting"))
        self.cdrtime_5.setText(_translate("MainWindow", "CDR time"))
        self.sender_id_5.setText(_translate("MainWindow", "Sender ID"))
        self.vendor_ani_5.setText(_translate("MainWindow", "Vendor ANi"))
        self.duration_5.setText(_translate("MainWindow", "Duration"))
        self.client_product_5.setText(_translate("MainWindow", "Client product"))
        self.msg_id_5.setText(_translate("MainWindow", "MSG ID"))
        self.trnsc_id_5.setText(_translate("MainWindow", "TRNSC ID"))
        self.send_time_5.setText(_translate("MainWindow", "Send time"))
        self.mccmnc_10.setText(_translate("MainWindow", "MCCMNC"))
        self.vendor_product_5.setText(_translate("MainWindow", "Vendor product"))
        self.status_5.setText(_translate("MainWindow", "Status"))
        self.text_sms_5.setWhatsThis(_translate("MainWindow", "<html><head/><body><p>Note, adding this field can increase the waiting time for the received report</p></body></html>"))
        self.text_sms_5.setText(_translate("MainWindow", "Text SMS"))
from PyQt5 import QtWebEngineWidgets
import file_rc
